@baseUri = http://localhost:5000/api
@contactId = 1

### Get all phones for a contact given the contact id
GET {{baseUri}}/contacts/{{contactId}}/phones

### Get all contacts
GET {{baseUri}}/contacts

### Get all contacts with name containing 'ski'
GET {{baseUri}}/contacts?search=ski
